#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0y
#  in conjunction with Tcl version 8.6
#    Sep 03, 2023 03:13:37 AM CDT  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_script = sys.argv[0]
_location = os.path.dirname(_script)

import mb_om2_support

_bgcolor = '#919191'  # X11 color: 'gray57'
_fgcolor = 'black'  # X11 color: #000000
_compcolor = '#8ba5cc' # Closest X11 color: 'LightSkyBlue3'
_ana1color = '#c5cc8b' # Closest X11 color: 'wheat3'
_ana2color = 'beige' # X11 color: #f5f5dc
_tabfg1 = 'black' 
_tabfg2 = 'black' 
_tabbg1 = 'grey75' 
_tabbg2 = 'grey89' 
_bgmode = 'light' 

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("788x316+928+460")
        top.minsize(1, 1)
        top.maxsize(2545, 1410)
        top.resizable(0,  0)
        top.title("Toplevel 0")
        top.configure(background="#919191")
        top.configure(highlightbackground="#919191")
        top.configure(highlightcolor="black")

        self.top = top

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(x=120, y=130, height=35, width=145)
        self.Frame1.configure(relief='solid')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="solid")
        self.Frame1.configure(background="#919191")
        self.Frame1.configure(highlightbackground="#919191")

        self.Frame2 = tk.Frame(self.top)
        self.Frame2.place(x=500, y=130, height=35, width=145)
        self.Frame2.configure(relief='solid')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="solid")
        self.Frame2.configure(background="#919191")
        self.Frame2.configure(highlightbackground="#919191")

        self.Button1 = tk.Button(self.top)
        self.Button1.place(x=630, y=20, height=31, width=101)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(background="#919191")
        self.Button1.configure(command=mb_om2_support.on_btnExit)
        self.Button1.configure(disabledforeground="#6d6d6d")
        self.Button1.configure(highlightbackground="#919191")
        self.Button1.configure(text='''Exit''')

def start_up():
    mb_om2_support.main()

if __name__ == '__main__':
    mb_om2_support.main()




